
String strDocumentDetails = 'Document Details';
String strCongratulations = 'Congratulations';
String strUserProfile = 'User Profile';
String strCreateUserProfile = 'Lets\'s create a user profile';
String strQuizzCompleted = 'Quizz __&&__ Completed';
String strInformation = 'Information';
String strSkip = 'Skip';
String strStart = 'START';
String strReStart = 'RE-START';
String strNumber = 'Number';
String strCountry = 'Country';
String strCountries = 'Countries';
String strSave = 'SAVE';
String strPhoto = 'Photos';
String strPhotoPlanning = 'Photo Planning';
String strSelectFromLibrary = 'Select other photo from library';
String strPreviewPhoto = 'Preview Photo';
String strAddPhoto = 'Add Photos';
String strCancel = 'Cancel';
String strPhotoAdjustText = 'ADJUST YOUR PHOTO FOR SHOLDER-HEAD PORTANT';
String strPhotoAdjustText1 = 'WHEN DONE SIMPLY CHECK THIS BUTTON';
String strPhotoAdjustDoneText = 'PROFILE PHOTO IS NOW READY';
String strNextPhotoText = 'LET\'S MOVE ON FOR NEXT PHOTO';
String strPreviewPhotoPlanning = 'Preview Photo Planning';
String strCardPhoto = 'Card Photo';
String strProfile = 'Profile';
String strCard = 'Card';

